issue-845-fix: True
resolve-type-alias: False
with-expecter: true
disable-version-string: True
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/services/graph/pkg/service/v0:
        config:
            dir: "mocks"
        interfaces:
            BaseGraphProvider:
            DrivesDriveItemProvider:
            DriveItemPermissionsProvider:
            HTTPClient:
            Permissions:
            RoleService:
            UsersUserProfilePhotoProvider:
    github.com/opencloud-eu/reva/v2/pkg/events:
        config:
            dir: "mocks"
        interfaces:
            Publisher:
    github.com/opencloud-eu/reva/v2/pkg/storage/utils/metadata:
        config:
            dir: "mocks"
        interfaces:
            Storage:
    github.com/opencloud-eu/reva/v2/pkg/rgrpc/todo/pool:
        config:
            dir: "mocks"
        interfaces:
            Selectable:
              config:
                filename: "gateway_selector.go"
    github.com/opencloud-eu/opencloud/services/graph/pkg/identity:
        config:
            dir: "pkg/identity/mocks"
        interfaces:
            Backend:
            EducationBackend:
    github.com/go-ldap/ldap/v3:
        config:
            dir: "pkg/identity/mocks"
        interfaces:
            Client:
                config:
                    filename: "ldapclient.go"
